# Generated by Django 3.2.23 on 2023-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('released_on', models.DateTimeField(verbose_name='date released')),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
    ]
