# Generated by Django 3.2.23 on 2023-11-20 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='released_on',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 13, 50, 43, 92085), verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='box_office',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='c_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='dvd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_votes',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='metascore',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='production',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rated',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='watched_on',
            field=models.DateTimeField(null=True, verbose_name='date watched'),
        ),
        migrations.AddField(
            model_name='movie',
            name='website',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default=2023, max_length=10),
            preserve_default=False,
        ),
    ]
