# Generated by Django 3.2.23 on 2023-11-21 06:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231120_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 6, 28, 43, 50514, tzinfo=utc), verbose_name='date added'),
        ),
    ]
